### ISSUE TITLE
drop in pdf quality compared to using iframes.

### ISSUE THREAD

**Issue by niksa27** [lfoppiano/structure-vision#3]
I am using this to load the pdf in frontend. I noticed that there is significant drop in pdf quality/ resolution compared to using iframes.

**Comment by lfoppiano** [comment]
Hi @niksa27, thanks for your interest. Could you please give me more information? Do you mean when you zoom in-out with the browser (ctrl+, ctrl-)? 

In general, this is just a demo for the PDF viewer https://github.com/lfoppiano/streamlit-pdf-viewer, which is rendering the PDF. The resolution would depend on the size of the frame, I think.

**Comment by niksa27** [comment]
Hi @lfoppiano thanks for your revert. I have attach two screenshot of pdf rendering using the streamlit-pdf-viewer and iframe in Streamlit. For same size of the frame the iframe has not lost the quality but the streamlit-pdf-viewer has lost and have reduced quality.
<img width="1104" alt="Iframe_Pdf_Quality'" src="https://github.com/lfoppiano/structure-vision/assets/58384570/9cc354ad-6a7a-4c02-942c-ea5378132291">
<img width="1103" alt="Streamlit-pdf-viewer-qulaity" src="https://github.com/lfoppiano/structure-vision/assets/58384570/54995ed5-7e0d-47f1-b6dd-8fd4ab22d9ff">

**Comment by lfoppiano** [comment]
Thanks! I've opened an issue redirecting here from the other project. I hope to find time to look into it.

**Comment by lfoppiano** [comment]
@niksa27 Which display do you use? Retina or not? Could you share some information about your environment?

**Comment by niksa27** [comment]
Hi @lfoppiano I have used multiple displays like macBookPro m1 and Hp desktop. It was same across all these displays.

**Comment by lfoppiano** [comment]
@niksa27 I managed to fix it in the latest version (0.0.11) of the streamlit-pdf-viewer.

**Comment by niksa27** [comment]
Thanks a lot. It seems good now.
